server:
  port: 9000
spring:
  ############################################################
  #
  # redis 配置
  #
  ############################################################
  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    database: 0
    # redis服务器地址（默认为localhost）
    host: 120.79.141.163
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password: Cdss!2018
    # redis连接超时时间（单位为毫秒）
    timeout: 3000
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 10
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 10
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1





redis:
  database: 0
  host: 120.79.141.163
  port: 6379
  password: Cdss!2018
  timeout: 3000
  pool:
    max-total: 100
    max-wait: -1
    max-idle: 8
    min-idle: 0
